sudo: required
addons:
  chrome: stable
language: node_js
before_script:
- npm install -g @angular/cli
node_js:
- node
script:
- npm run test-ci
- npm run build-ci
before_deploy:
- cd dist/ngx-aircal
deploy:
  provider: npm
  email: chris.swarb@gmail.com
  skip_cleanup: true
  on:
    tags: true
    repo: cswarb/ngx-aircal
  api_key:
    secure: vDthR23AyT2ldpWeo0j4tPxf79YGGwh0UlOI72/6kF4/BDMe9z6QN34I79Qfu4Yq8Ibv2kLV4gp3vUmCwCK8sMf/08oWxM7vfPMj+1FScC5LAR3/+dwndyjtuAKccY1UcCK/BGyARFi3uhxfm+La60t1y35t+ybdaMq5UKXBi1orReGdvjg1iigIcmMNjLsPSWPxFCDdeMo4ZGJf+uWXhCljcZ5ByV407Cdp1TFgjax1CDtNtiaA2DUIeBWTIGvuXKGH4wgVESIu3OC0BLw3uKcPgLo1DV2YB/HjHcsGIRe/lmL+gmbra3KFoaZTj1X45spJRlF9P+xv31ulWXCiLw4rw2xbPeR/bVwm3Nd2vqJjHYeqxZV9VQrQOeJhh0+9h7PNrGfmIet8xohuVndrg/1b77XgKqiorqmN72SY3sHPAus/MQSChchUj134t5KV7ou1spMKvIZtBBu4Q06uzRq1QDATkp6UGDJFxb7gjwRZBKuj0q0d+kA2Oezrtz/Sk7pqnRfXGNS8e3IEmi8RRBlafhoS8t97fipb73IRPfUNL4gFX19EMVKBAsm0wgSxyNf47lRCERDL5YSKlq98lSi0Z7aRffJTF5o7aeT3PI/Dr+h/XRODMKon1XMHwic9sCk25OXn1NNji/HF5uVl0thfADvbOzqUJJlT09kL+B8=
